version: '3.8'
networks:
  mailradio-network:
    driver: bridge 
services:
  nginx-app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
  postgres-db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - mailradio-network
  mailradioapp:
    image: "jaspalsregistry.azurecr.io/platin-v2-apps-mailradio:latest"
    container_name: "platin.v2.apps.mailradio"
    environment:
        SQLDB: "Password={DB_PASSWORD};Username={DB_USER};Database=postgres;Host=postgres-db"
        ASPNETCORE_URLS: "http://+:5000"
    ports:
      - '5000:5000'
    networks:
      - mailradio-network
